import "./globals.css";
import { c } from "../utils/index";
import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mr",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={c(inter.variable, manrope.variable, "bg-light font-mr")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
