import "./globals.css";
import { c } from "../utils/index";
import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import Header from "@/components/header/header";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mr",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={c(
          inter.variable,
          manrope.variable,
          "font-mr bg-light"
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
